import Head from 'next/head'
import Image from 'next/image'
import Header from '@components/Header'
import Container from '@components/Container'
import Button from '@components/Button'
import products from '@data/products.json'

import styles from '@styles/Home.module.scss'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Card Store USA</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <main className={styles.main}>
        <Container>
          <h1>Hyper Bros. Trading Cards</h1>
          <h2>Available Cards</h2>
          <ul className={styles.products}>
            {products.map((product) => {
              return (
                <li key={product.id}>
                  <Image
                    src={product.image}
                    alt={`${product.title} Card`}
                    width='864px'
                    height='1200px'
                  />
                  <h3 className={styles.productTitle}>{product.title}</h3>
                  <p className={styles.productPrice}>${product.price}</p>
                  <Button>Add to Cart</Button>
                </li>
              )
            })}
          </ul>
        </Container>
      </main>

      <footer className={styles.footer}>
        &copy; Hyper Bros. Trading Cards, {new Date().getFullYear()}
      </footer>
    </div>
  )
}
